apiVersion: v1
entries:
  camel-dashboard-console:
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2025-11-19T18:50:01.31647555+01:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 942382a4f636399ab9891020eed00a0bb4fd2f3c833e2b8fcb45757c2ac708dc
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.3.0.tgz
    version: 0.3.0
generated: "2025-11-19T18:50:01.315731528+01:00"
