apiVersion: v1
entries:
  camel-dashboard-console:
  - annotations:
      charts.openshift.io/name: Camel Dashboard OpenShift Console plugin
    apiVersion: v2
    appVersion: 0.4.0
    created: "2026-02-12T15:40:28.816979627+01:00"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 09069e0fc2db84445e478b2f4144c35db699c28caf0f7533a66a1f346afaf01c
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - camel
    - dashboard
    - console
    - react
    kubeVersion: '>= 1.33'
    maintainers:
    - email: gfournier@apache.org
      name: gansheer
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.4.0.tgz
    version: 0.4.0
generated: "2026-02-12T15:40:28.816421833+01:00"
