name: release-0.x.x

on:
  pull_request:
    branches:
      - "release-0.1.x"
      - "release-0.2.x"
  push:
    branches:
      - "release-0.1.x"
      - "release-0.2.x"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Build plugin
        run: make build

      - name: Lint plugin
        continue-on-error: true
        run: make lint

      - name: Log in to registry
        if:  github.ref == 'refs/heads/release-0.1.x' || github.ref == 'refs/heads/release-0.2.x'
        id: login-registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build plugin container
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=quay.io/camel-tooling/camel-openshift-console-plugin image

      - name: Push plugin container
        if:  github.ref == 'refs/heads/release-0.1.x' || github.ref == 'refs/heads/release-0.2.x'
        shell: bash
        run: |
          make CUSTOM_PLUGIN_IMAGE=quay.io/camel-tooling/camel-openshift-console-plugin push
